### PR TITLE
Added 626

### LINKED ISSUE #270: Error code 626 - Child was reported as a mother but the date of birth of the first child is before the current year which contradicts with the mother status recorded last year.
#### Error code
626
#### Description to display
Child was reported as a mother but the date of birth of the first child is before the current year which contradicts with the mother status recorded last year.
#### DfE Long-form description of error
If a child has been recorded as being a mother in the latest reporting year and the date of birth of the first child is in a previous year, then the mother status must be consistent between the year the mother's child was born and the latest year.
#### DfE suggested coding
If `<MOTHER>` = '1' and previous year `<MOTHER>` = '0' or null then `<MC_DOB>` must be >= `<COLLECTION_START>`

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

### PR DESCRIPTION
**Pull request by PhilDeakin**
As above

### CODE REVIEW

**Comment by PhilDeakin** [comment]
Just the 626 one.

**Comment by PhilDeakin** [comment]
Can't work out why this is failing.

**Comment by dezog** [comment]
Hi Phil sorry there's a bit of a backlog at the moment. I'll try and give this one a proper look later today, just tying up some loose ends for release now!

At a glance it looks to be ot do with NaT values and 'tz' (timezone info?), ie probably missing/invalid dates, and/or wrong datetime type

**Comment by PhilDeakin** [comment]
> 

No problem

**Comment by dezog** [comment]
Apologies for the ridiculously long delay, Phil, I totally lost track of this one over the Christmas break, and it's taken a while to get round the pull request queue...

Took me a while to get to the bottom of this, weirdly it was passing pytest just fine for me locally, but raising that weird exception about timezone info when the checks ran on the GitHub side. 

The comparison to collection_start in the `.query()` call was throwing that error - seems like a bug where pandas thinks it's a different type of datetime object, but I've no idea why it'd only be failing on GitHub...

Anyway, I wrote that bit out in full instead and now it works 🤷. I also changed the MOTHER comparison to compare them as numbers instead of strings following conversation on https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/issues/499

**Review by dezog — APPROVED** [review]
Good job - your code was fine, it was most likely failing due to a bug! (See other comment)

**Pull request merged**
