### PR TITLE
Added error 630

### LINKED ISSUE #272: Error code 630 - Information on previous permanence option should be returned.
#### Error code
630
#### Description to display
Information on previous permanence option should be returned.
#### DfE Long-form description of error
A new episode has started in the latest reporting year, with the reason for new episode being S, therefore data for items relating to previous permanence option must be returned.  Data items:  Previous permanence option, Local authority code where previous permanence option was arranged (unless previous permanence option is Z1), Date of order (unless previous permanence option is Z1),  must be returned for all children starting to be looked after 1 April of the current collection year, this includes children with legal status of V3 or V4.
#### DfE suggested coding
If `<RNE>` = 'S' then `<PREV_PERM>` must be provided as should `<LA_PERM>` and `<DATE_PERM>` if `<PREV_PERM>` is not = 'Z1'

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

### PR DESCRIPTION
**Pull request by PhilDeakin**
Added error 630

### CODE REVIEW

**Review by dezog — CHANGES_REQUESTED** [review]
Great job on this, it's a pretty complex rule. 

The only things that stand out to me are:

1.  On more complicated rules like this I think it would be good to include a few comments in the `_validate()` function so the thought process behind it is explicit -this should make it easier if we find we need to tweak anything down the line, and also help me review the code a bit faster too

2. This part of the description:

>[previous permanence fields] must be returned for all children starting to be looked after 1 April of the current collection year, this includes children with legal status of V3 or V4.  

This seems to imply that if an `RNE == 'S'` episode started before the current collection year, they don't need to be included in the PreviousPermanence table (though weirdly it's not mentioned in the 'Coding Description'). Does that sound right to you? 

image

**Comment by PhilDeakin** [comment]
Think you're right about it needing to look at RNE of 'S' in this financial year only, I've amended it to do that.

**Review by dezog — APPROVED** [review]
Good stuff - approved

Great work this week, have a nice weekend

**Comment by dezog** [comment]
closes #272

**Pull request merged**
