### PR TITLE
Added error 355

### LINKED ISSUE #146: Error code 355 - Episode appears to have lasted for less than 24 hours.
#### Error code
355
#### Description to display
Episode appears to have lasted for less than 24 hours.
#### DfE Long-form description of error
Episodes cannot start and cease on the same day.  An episode which started and ended on the same day should not be shown on the data collection record.
#### DfE suggested coding
`<DECOM>` and `<DEC>` cannot be the same date

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

### PR DESCRIPTION
**Pull request by PhilDeakin**
Rules 141 & 147 enforce that DECOM and DEC are in the format dd/MM/yyyy so I think we're fine testing as a string.
astype(str) probably isn't needed, but won't matter.

### CODE REVIEW

**Review by dezog — CHANGES_REQUESTED** [review]
Hey Phil, 

Nice work, the validation looks good - as you say, converting the dates to datetime wouldn't make a difference in this case. 

For completeness I would add one more test case where the DEC is before the DECOM, to ensure this error can't trigger alongside rule #356. Shouldn't make any practial difference, but it's good to be sure, just in case we make changes to the code in future.

**Comment by PhilDeakin** [comment]
@dezog Done

**Review by dezog — APPROVED** [review]
Looks good. Nice one, Phil 👍

**Comment by dezog** [comment]
Closes #327

**Pull request merged**
