### PR TITLE
Added 118

### LINKED ISSUE #23: Error code 118 - Date of decision that a child should no longer be placed for adoption is before the current collection year or before the date the child started to be looked after.
#### Error code
118
#### Description to display
Date of decision that a child should no longer be placed for adoption is before the current collection year or before the date the child started to be looked after.
#### DfE Long-form description of error
If the decision is that a child should no longer be placed for adoption, then the date of this decision cannot be before the start of the current collection year or date they started to be looked after.
#### DfE suggested coding
If provided `<DATE_PLACED_CEASED>` must not be prior to `<COLLECTION_START_DATE>` or `<DECOM>` of the earliest episode with an `<LS>` not = 'V3' or 'V4'

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

### PR DESCRIPTION
**Pull request by tab1tha**
Added 118

Closes #23

### CODE REVIEW

**Comment by dezog** [comment]
this appears to be working fine - CHILD 102's first episode DECOM and the COLLECTION_START are both before their DATE_PLACED_CEASED.

So row 3 should not be an error. Does that sound right?

**Comment by tab1tha** [comment]
> this appears to be working fine - CHILD 102's first episode DECOM and the COLLECTION_START are both before their DATE_PLACED_CEASED.
> 
> So row 3 should not be an error. Does that sound right?

Ohhh that sounds about right. I'll try again

**Comment by tab1tha** [comment]
The functionality that skips over the first DECOM if its LS is V3 or V4 is not working yet.

**Review by dezog — APPROVED** [review]
Looks good, nice one Tambe

**Pull request merged**
